### ISSUE TITLE
setup Spring Postgres connection using service name 

### ISSUE THREAD

**Issue by pachecopaulo** [pachecopaulo/kubernets-multi-container-app#1]
Currently the **server-deployment.yaml** file makes usage of **postgres-cluster-ip-service** to setup the URL to connect to postgres however spring boot does not recognise that as a valid URL for configuration and the Kubernets POD is never started properly.

Log from the POD:

```
Caused by: java.lang.IllegalArgumentException: URL must start with 'jdbc'
	at org.springframework.util.Assert.isTrue(Assert.java:118) ~[spring-core-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
	at org.springframework.boot.jdbc.DatabaseDriver.fromJdbcUrl(DatabaseDriver.java:280) ~[spring-boot-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.boot.autoconfigure.jdbc.DataSourceProperties.determineDriverClassName(DataSourceProperties.java:230) ~[spring-boot-autoconfigure-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
```

**Comment by pachecopaulo** [comment]
Currently the **server-deployment.yaml** file makes usage of **postgres-cluster-ip-service** to setup the URL to connect to postgres, but spring boot does not recognise that as a valid URL for configuration.

**Comment by pachecopaulo** [comment]
The issue has been fixed within the server-deployment.yaml file using
```
env:
   - name: SPRING_DATASOURCE_URL
     value: jdbc:postgresql://postgres-cluster-ip-service/postgres
```
